sonar.projectKey=nova136_onedelivery-guardian-agent
sonar.organization=nova136
sonar.projectName=Guardian Agent
sonar.projectVersion=1.0
sonar.branch.name=master

sonar.sources=./src
sonar.tests=./src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**
