sonar.projectKey=nova136_onedelivery-user
sonar.organization=nova136
sonar.projectName=User Service
sonar.projectVersion=1.0

sonar.sources=./src
sonar.tests=./src,./test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**
