import { AgentCallbackStateType } from "../agent-callback.state";
import { PiiRedactionService } from "../../modules/pii-redaction/pii-redaction.service";
import { PromptShieldService } from "../../modules/prompt-shield/prompt-shield.service";

export interface CallbackPreProcessingDependencies {
    piiService: PiiRedactionService;
    promptShield: PromptShieldService;
}

export const createCallbackPreProcessingNode = (
    deps: CallbackPreProcessingDependencies,
) => {
    return async (state: AgentCallbackStateType) => {
        const { piiService, promptShield } = deps;

        const redacted = await piiService.redact(state.agent_message);

        // We run the agent callback through Prompt Shield but NOT Input Validator because:
        // 1. Input Validator is designed for raw user input (checking length, gibberish, basic structure).
        // 2. The agent's output is already structured and generated by an LLM, so it won't fail basic input checks.
        // 3. However, the agent might have been compromised by a prompt injection attack from the user.
        // 4. Therefore, we use Prompt Shield to detect if the agent is echoing or acting on malicious payloads
        //    before passing it to downstream extraction/evaluation nodes.
        const isSuspicious = await promptShield.isSuspicious(redacted);

        let finalRedacted = redacted;
        if (isSuspicious) {
            finalRedacted = promptShield.wrapUntrustedData(
                "suspicious_agent_callback",
                redacted,
            );
        }

        return {
            redacted_message: finalRedacted,
            is_safe: !isSuspicious,
        };
    };
};
