FROM node:24-alpine

ARG SERVICE_NAME
ARG EXPOSE_PORT

WORKDIR /workspace

RUN apk add --no-cache make g++ python3

RUN apk update

RUN apk upgrade

RUN npm install -g npm@latest

COPY package*.json ./

RUN npm ci --legacy-peer-deps && \
    npm install @nestjs/cli --no-save --legacy-peer-deps

COPY . .
RUN rm -rf .env

RUN ./node_modules/.bin/nest build ${SERVICE_NAME}

ENV SERVICE_NAME=${SERVICE_NAME}
EXPOSE ${EXPOSE_PORT}
CMD ["sh", "-c", "node ./dist/apps/$SERVICE_NAME/main.js"]
