export enum IncidentType {
  LATE_DELIVERY = 'LATE_DELIVERY',
  MISSING_ITEMS = 'MISSING_ITEMS',
  WRONG_ORDER = 'WRONG_ORDER',
  DAMAGED_PACKAGING = 'DAMAGED_PACKAGING',
  PAYMENT_FAILURE = 'PAYMENT_FAILURE',
  OTHER = 'OTHER',
}